### ISSUE TITLE
[Bug] PF2 action icons not rendering on ipad for statblocks

### ISSUE THREAD

**Issue by pamput** [Obsidian-TTRPG-Community/Fantasy-Statblocks-CSS-Development#4]
PF2 action icons are not rendering on ipad for statblocks. 

After a bit of debugging it seems the family face ordering in the css snippet overwrites the action icons of the stat blocks on ipad. 
Currently this is the list applied in the snippet that should introduce the icons:

```css
    font-family: system-ui, "Pathfinder", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
```

It's likely that `system-ui` takes precedence and overwrites the action icons and turns them back into arrows.

# Solution 1

Theoretically this  **should** be easily fixable by setting the order as:

```css
    font-family: "Pathfinder",  system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
```

Problem with the above is the injected font doesn't contain only the action characters but also a couple more, including a blank 0 (zero). Blank as in "the type is actually an empty picture".

If you try to apply the above all the zeroes disappear:

Pre change:

![image](https://github.com/Obsidian-TTRPG-Community/ObsidianTTRPGShare/assets/3295190/8cf61205-b67f-42fe-807a-6caca8863267)

Post change:

![image](https://github.com/Obsidian-TTRPG-Community/ObsidianTTRPGShare/assets/3295190/2b7e16df-78e3-4e91-9293-4ff7064fc2fe)

Note the "imprecise scent 30" loses its zero.

# Solution 2

Select the unicode range or nuke the broken "zero character" from the font like this:

```css
@font-face {
    font-family: "Pathfinder";
    src: url("data:application/x-font-ttf;charset=utf-8;base64,lookatmemomimafont") format("truetype");
    font-weight: normal;
    font-style: normal;
    font-display: block;
    unicode-range: U+2B32, U+2B3A, U+2B3B, U+2B3D, U+2B53;
}
```

Unfortunately this doesn't work. It's likely that this font is injected in more than one place with the name "Pathfinder" and gets overwritten.

# Solution 3

This works:

```css
/* FONTS */
/* Main Font */
@font-face {
    font-family: "Pathfinder";
    src: url("data:application/x-font-ttf;charset=utf-8;base64,lookatmemomimafont") format("truetype");
    font-weight: normal;
    font-style: normal;
    font-display: block;
    unicode-range: U+2B32, U+2B3A, U+2B3B, U+2B3D, U+2B53;
}


@font-face {
    font-family: "PathfinderActions";
    src: url("data:application/x-font-ttf;charset=utf-8;base64,lookatmemomimafont") format("truetype");
    font-weight: normal;
    font-style: normal;
    font-display: block;
    unicode-range: U+2B32, U+2B3A, U+2B3B, U+2B3D, U+2B53;
}

.Pathfinder {
    font-family: "PathfinderActions";
}

.statblock.basic-pathfinder-2e-layout .statblock-markdown p {
    font-family: PathfinderActions, system-ui, Pathfinder, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;
}
```

It's crude, but it works. It's almost 4am on this side of the pond so I'm too tired to make a PR. If someone smarter than me wants to pick this up and make a better fix, feel free. Happy to elaborate if there should be questions (once I'm rested...).

I'm going to sleep 💤

**Comment by sigrunixia** [comment]
Moving this to the Pathfinder 2E Statblock Dev Repo.

**Comment by pamput** [comment]
I suspected it was statblock's fault yesterday, but it was late and I wanted to drop all the information I had in my brain before going to bed.

https://github.com/Obsidian-TTRPG-Community/Pathfinder-2E-Statblocks-Development/blob/master/src/scss/components/_font.scss#L7

Here I think is the culprit font. Is there any reason why there is a blank zero in among the types? Just an error or some font wizardry I'm not aware about?

**Comment by sigrunixia** [comment]
On my side, looking at the source font, there is no blank 0 included in the font family. Only the 5 action glyphs. So I suspect what may be happening is on iPad that 0 is being read as the start of a pathfinder glyph but it finds nothing. 

We'll likely need to add media screen rules to Address the iPad solution specifically. We're going to be working on a CSS update in #3 and we'll include this fix in it.

**Comment by mProjectsCode** [comment]
I don't own any Apple device so I will be of no help here xD

**Comment by sigrunixia** [comment]
I got you covered! :)

**Comment by pamput** [comment]
> On my side, looking at the source font, there is no blank 0 included.

My knowledge of font types is very limited, but this is what I see via font forge:

![image](https://github.com/Obsidian-TTRPG-Community/Pathfinder-2E-Statblocks-Development/assets/3295190/794f8248-768a-4ef4-acdd-efd5933284c2)

Also I can confirm that using either a modified version of this font with the zero type nuked OR the unicode range in my css snippet fixes the issue (beside the font family name clash). For reference, these are the characters I see in the font type:

![image](https://github.com/Obsidian-TTRPG-Community/Pathfinder-2E-Statblocks-Development/assets/3295190/13884f3e-9019-457c-9117-e398e3596e24)

The unicode range targets these symbols directly.

> I don't own any Apple device so I will be of no help here xD

Happy to lend a hand here.

**Comment by sigrunixia** [comment]
Bah. I wasn't using font forge, but if it says its there, its there. :( We'll get that fixed then.

**Comment by pamput** [comment]
> Bah. I wasn't using font forge, but if it says its there, its there. :( We'll get that fixed then.

I'm happy to provide you with a ttf without the zero type. For reference, this type also contains:

* U+0000: control character
* U+0001: control character
* U+0020: space
* U+0030: digit zero
* U+FFFD: replacement character

You probably want to get rid of space too.

**Comment by sigrunixia** [comment]
Agreed on the space and we'll certainly take it. Saves us some work. :)

**Comment by pamput** [comment]
Sorry for the delay, it's been a busy couple of days at work :)

Here is the css including the font with the space and zero digit char removed.

```css

@font-face {
    font-family: "PathfinderActions";
    src: url("data:application/x-font-ttf;charset=utf-8;base64,AAEAAAANAIAAAwBQRkZUTaBf/YkAAAkkAAAAHEdERUYAJQAAAAAJDAAAABhPUy8yDzE5wAAAAVgAAABgY21hcIUPLFwAAAHcAAABcGdhc3AAAAAQAAAJBAAAAAhnbHlmv0sljgAAA2AAAAIwaGVhZCgbkG4AAADcAAAANmhoZWEMNQhqAAABFAAAACRobXR4IOUAhwAAAbgAAAAkbG9jYQGoAlQAAANMAAAAFG1heHAADgA/AAABOAAAACBuYW1l5gKtSAAABZAAAAMGcG9zdJP9aoAAAAiYAAAAbAABAAAAARmaJrDlgl8PPPUACwQAAAAAAN/r3gMAAAAA4J1UVAAA/8AIcwPAAAAACAACAAAAAAAAAAEAAAPA/8AAAAigAAAAAAhzAAEAAAAAAAAAAAAAAAAAAAAJAAEAAAAJAD0ABAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAwVCAZAABQAAApkCzAAAAI8CmQLMAAAB6wAzAQkAAAAAAAAAAAAAAAAAAAABAAAAIAAAAAAAAAAAAAAAAABAAAArUwPA/8AAQAPAAEAAAAABAAAAAAAAAAAAAAAgAAEEAAAAAAAAAAFVAAAAAAAABFAAKAaAACAEAAACCKAALQQgABAAAAADAAAAAwAAABwAAQAAAAAAagADAAEAAAAcAAQATgAAAAwACAACAAQAASsyKz0rU//9//8AAAAAKzIrOitT//3//wAA1NIAANS1AAAAAQAMAAAADAAAABAAAAABAAMABQAGAAAABwAAAAABBgAAAQMAAAAAAAABAgAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAIABAAeACgALwA8AEYAAEAAAAAAAAAAAACAAA5AgABAAAAAAAAAAAAAgAAOQIAAgAoACIEMwNlADcAPAAAASYnJicmJyYHBgcGBwYHBgc2NzY3Njc2NzYXFhcWFxYXFgcGBwYHBgcGBwYnFhcWNzY3Njc2NzYBBSc3AQQdFzs8VFNlZWpLQUEzMyQkERUdHSMkKSouVVFRQ0QwMBISEBEsK0RDVRwcGxs/REVFalRUNjYVFPyNAeltOP5MAkdHOTklJQ0ODwsYGCIiKyovGhYXEhINDQcMCwsdHi4uOTo3Ny0uISAMBAECAQ4DAwoPKSg5OEVE/opnldf++wAAAAMAIP/BBmADvwAFAAkADwAACQEHCQEXAQcXNyUBBxcHFwQa/gH2AQj++Pb+vLe3twTS/kDZ6OjZAcAB//f++P749wK2t7e3CAHA2Ojo2QAAAgAC/8AD/gPAAAUACQAACQEHCQEXAQcXNwP+/gD3AQn+9/f+u7e3twHAAgD3/vf+9/cCt7e3twAEAC3/wAhzA8AABQALAA8AFQAACQEHCQEXCQEHFwcXAQcXNyUBBxcHFwQp/gD3AQn+9/cGSv6Yr7u7r/nZt7e3BNz+P9rp6doBwAIA9/73/vf3AgoBaK66u64CFre3twgBwdno6dkAAAMAEP/ABBADwAAEAAkADwAACQU3FwcnASc3JzcBAhT9/AH9AgP+BP64bW1tbQE3cfv1fAFnA8D9+v4GAgMB/f4QbW1tbf6Ecfv2fP6ZAAAAAAASAN4AAQAAAAAAAQAKABYAAQAAAAAAAgAHADEAAQAAAAAAAwAKAE8AAQAAAAAABAAKAHAAAQAAAAAABQALAJMAAQAAAAAABgAKALUAAQAAAAAACgA2AS4AAQAAAAAADQAXAZUAAQAAAAAADgAoAf8AAwABBAkAAQAUAAAAAwABBAkAAgAOACEAAwABBAkAAwAUADkAAwABBAkABAAUAFoAAwABBAkABQAWAHsAAwABBAkABgAUAJ8AAwABBAkACgBsAMAAAwABBAkADQAuAWUAAwABBAkADgBQAa0AUABhAHQAaABmAGkAbgBkAGUAcgAAUGF0aGZpbmRlcgAAUgBlAGcAdQBsAGEAcgAAUmVndWxhcgAAUABhAHQAaABmAGkAbgBkAGUAcgAAUGF0aGZpbmRlcgAAUABhAHQAaABmAGkAbgBkAGUAcgAAUGF0aGZpbmRlcgAAVgBlAHIAcwBpAG8AbgAgADEALgAxAABWZXJzaW9uIDEuMQAAUABhAHQAaABmAGkAbgBkAGUAcgAAUGF0aGZpbmRlcgAAUABhAHQAaABmAGkAbgBkAGUAcgAgADIAZQAgAEEAYwB0AGkAbwBuACAARwBsAHkAcABoAHMACgBGAG8AbgB0ACAAZwBlAG4AZQByAGEAdABlAGQAIABiAHkAIABJAGMAbwBNAG8AbwBuAC4AAFBhdGhmaW5kZXIgMmUgQWN0aW9uIEdseXBocwpGb250IGdlbmVyYXRlZCBieSBJY29Nb29uLgAAUABhAGkAegBvACAAQwBvAG0AbQB1AG4AaQB0AHkAIABMAGkAYwBlAG4AcwBlAABQYWl6byBDb21tdW5pdHkgTGljZW5zZQAAaAB0AHQAcABzADoALwAvAHAAYQBpAHoAbwAuAGMAbwBtAC8AYwBvAG0AbQB1AG4AaQB0AHkALwBjAG8AbQBtAHUAbgBpAHQAeQB1AHMAZQAAaHR0cHM6Ly9wYWl6by5jb20vY29tbXVuaXR5L2NvbW11bml0eXVzZQAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAECAAIBAwEEAQUBBgEHAQgHdW5pMDAwMAd1bmkwMDAxB3VuaTJCMzIHdW5pMkIzQQd1bmkyQjNCB3VuaTJCM0QHdW5pMkI1MwABAAH//wAPAAEAAAAMAAAAEAAAAAIAAAAEAAAAAgAAAAAAAQAAAADf1ssxAAAAAN/r3gMAAAAA4J1UVA==") format("truetype");
    font-weight: normal;
    font-style: normal;
    font-display: block;
    unicode-range: U+2B32, U+2B3A, U+2B3B, U+2B3D, U+2B53;
}

```

For good measure I'm also attaching the ttf should you find it useful.

[Pathfinder-noSpaceNoZero.zip](https://github.com/Obsidian-TTRPG-Community/Pathfinder-2E-Statblocks-Development/files/11618368/Pathfinder-noSpaceNoZero.zip)

Let me know if I can help in any other way.
